version: '3.4'

services:
  sda.mk.carparts:
    image: sdamkcarparts
    build:
      context: .
      dockerfile: SDA.MK.CarParts/Dockerfile
    depends_on:
     - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "dev"
      ACCEPT_EULA: "Y"