version: '3.4'

services:
  sda.mk.carparts:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - CONNECTIONSTRINGS__DATABASE=Server=db;Database=master;User=sa;Password=Strong!Passw0rd;
    ports:
      - "5100:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  db:
    ports:
      - "1433:1433"
    volumes:
     - db-volume:/var/opt/mssql/data

volumes:
  db-volume: